apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mjgj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mjgj
    app.kubernetes.io/part-of: byoc-app-dcnt
  name: mjgj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: mjgj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: mjgj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-iurm-tenant/byoc-app-dcnt/mjgj@sha256:a369c2efdf5b0f797da922a0b59fd20ca526b2c1d5560b6890b42e5a10deb160
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
