apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mjgj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mjgj
    app.kubernetes.io/part-of: byoc-app-dcnt
  name: mjgj
spec:
  rules:
  - host: mjgj-byoc-iurm-tenant.apps.c2b7e95c9d7b38a9ad77.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: mjgj
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
